### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by deanhtid** [dannysteenman/vscode-cloudformation-snippets#10]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would love it if this plugin had support for JSON as well as YAML. I think a lot of developers out there probably use JSON and this plugin would be great for productivity. 

**Describe alternatives you've considered**
Unfortunately they’re isn’t an alternative. Not what I’ve found anyways.

**Comment by mayormaier** [comment]
I'd like to circle back here... is this something that will get support in the future?

**Comment by dannysteenman** [comment]
There might be support for it in the long term, but for now, I don't have time to build that feature. If you want to help out @mayormaier or @deanhtid, I'm open to PR's ;)

**Comment by dannysteenman** [comment]
I finally found the time to implement this feature see: https://github.com/dannysteenman/vscode-cloudformation-snippets/pull/15

Update your vscode extension to version 4 to see the new autocomplete for JSON files!
