### ISSUE TITLE
Produce sample for IAM Policies

### ISSUE THREAD

**Issue by felipe1982** [dannysteenman/vscode-cloudformation-snippets#13]
**Is your feature request related to a problem? Please describe.**

When I create a Policy, I expect the plugin to provide an example outline of the YAML required to form a syntactically correct IAM policy

**Describe the solution you'd like**
I would like an example policy to be provided when I make an IAM policy, role, etc.

**Describe alternatives you've considered**
I need to re-use my own code to produce a starting point from which to create my policy

**Additional context**

```

Resources:
  VpcFlowLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: vpc-flowlogs
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
            Effect: Allow
            Resource: "*"
      Roles:
        - !Ref VpcFlowLogsRole

  VpcFlowLogsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: vpc-flowlogs
      Description: "Permit VPC to write Flow Logs to CloudWatch."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole

```

Here is an example which can be used as an example when making a role or policy or other IAM resource.

**Comment by dannysteenman** [comment]
Creating policies is really custom work and it's not helpful to add a bunch of dummy example policies since everyone requires their own set of permissions. I would highly recommend using this tool to generator your IAM policies:

https://www.awsiamactions.io/generator
