### ISSUE TITLE
Gitpod/OpenVSX Support?

### ISSUE THREAD

**Issue by Grunet** [dannysteenman/vscode-cloudformation-snippets#14]
**Is your feature request related to a problem? Please describe.**
Afaict it's not possible to use this extension on [Gitpod](https://gitpod.io).

**Describe the solution you'd like**
I'd like to be able to install this extension in a Gitpod workspace

**Describe alternatives you've considered**
Not using Gitpod...which maybe I will because I really like this extension!

**Additional context**
I wrote up a [similar request](https://github.com/aws-cloudformation/cfn-lint-visual-studio-code/issues/219) on the cfn-lint extension's repository just now, so I'll copy what I wrote there below:

Just learned that only extensions published to the [OpenVSX](https://open-vsx.org/) registry will work on[ Gitpod](https://gitpod.io), and was curious if the maintainers of this repo would be interested in publishing there as well.

The steps for doing so are listed [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). 1-4 have to do with setting up an account and generating a token, then the last step discusses how to actually perform the publish.

It seems like updating the Github workflow publish pipeline to also publish to OpenVSX could look something like [this](https://github.com/github/vscode-codeql/blob/main/.github/workflows/release.yml#L150).

**Comment by dannysteenman** [comment]
Thank you for opening this request @Grunet and supplying the neccesary information. This should be an easy fix from my end indeed, I'll pick it up if I got some time soon!

**Comment by dannysteenman** [comment]
Done: https://open-vsx.org/extension/dsteenman/cloudformation-yaml-snippets
