### ISSUE TITLE
Add these helpful snippets to neovim

### ISSUE THREAD

**Issue by mithun-daa** [dannysteenman/vscode-cloudformation-snippets#16]
**Is your feature request related to a problem? Please describe.**
These snippets will work right out of the box for neovim users that use the https://github.com/rafamadriz/friendly-snippets plugin. 
It should be a straightforward copy. 

**Describe the solution you'd like**
The snippets need to be  synced with the `friendly-snippets` repo

**Describe alternatives you've considered**
I could submit a PR to the other repo but I wasn;t sure if that was acceptable.

**Additional context**
Thank you for the great work.

**Comment by dannysteenman** [comment]
Sound like a great idea but I think you should open up a github issue on https://github.com/rafamadriz/friendly-snippets and ask them to include the snippets from my vscode extension? I'm not sure what I can do from my side to help you.

**Comment by mithun-daa** [comment]
I can. I just wanted to run it by you if it was acceptable before doing so.

**Comment by dannysteenman** [comment]
Please let me know if you need any input from me :)
