### ISSUE TITLE
Hangup at json file sentences select.

### ISSUE THREAD

**Issue by Jun-KODAMA-SCSK** [dannysteenman/vscode-cloudformation-snippets#18]
Type: <b>Bug</b>

* Open json file( SCP/IAM policy file)
* select multi lines at mouse
* click selected area.
 -> no responce and display [long time no responce, retry / shutdown / wait ]dialog ( written in Japanese )

Extension version: 5.10.0
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.65GB (3.94GB free)|
|Process Argv|--crash-reporter-id e75492c7-416e-4410-a49f-f3b2d78893b8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by dannysteenman** [comment]
In v5.10.0 I've added support for all the nested properties of all cloudformation resources: https://github.com/dannysteenman/vscode-cloudformation-snippets/issues/11#issuecomment-2198635659

However this resulted in a massive vscode snippet file for json and yaml (322k of raw vscode snippet lines) this might've caused the slowdown on your machine. I've pushed a new fix in v5.11.0: https://github.com/dannysteenman/vscode-cloudformation-snippets/commit/c0471f5c4d1a6d4013551190e94e580b96a4b84e that addresses this massive codesnippet file by setting a hardcap on resources to not go above 400 lines. 

Some of the resources that contain a tremendous amount of nested properties are:

```
AWS::WAFv2::WebACL: 911 lines
AWS::QuickSight::Analysis: 11064 lines
AWS::QuickSight::Template: 11048 lines
AWS::QuickSight::Dashboard: 11087 lines
AWS::KinesisFirehose::DeliveryStream: 657 lines
AWS::Lex::Bot: 4658 lines
AWS::MediaLive::Channel: 842 lines
```

Please let me know if the new version fixed the issue.
