### ISSUE TITLE
AWS cfn Intrinsic funtions

### ISSUE THREAD

**Issue by raghu88-scm** [dannysteenman/vscode-cloudformation-snippets#4]
Hello,
Thank you for creating this extension for AWS CFN and am finding very helpful. Now I am creating my cfn templates very efficiently.
When I start typing intrinsic functions (Equals, And, Or, Not, Select, GetAZs) they don't pop up.
Some functions show up like ( If and one other function).
Am i not typing the right keywords for them to show up?

I am very new to github and vs code, So my layman question.
Is this something I can add to my local install? If yes some directions/links is appreciated.
If you can incorporate in you next build that will be awesome.

Thank you for your contribution.

**Comment by dannysteenman** [comment]
Hi Raghu8842, 

The intrinsic function snippets didn't exist yet in this VS Code extension. I've updated it now and added this feature.
