### ISSUE TITLE
Provide support for AWS Serverless Application Model

### ISSUE THREAD

**Issue by felipe1982** [dannysteenman/vscode-cloudformation-snippets#6]
Please provide support for Types such as `AWS::Serverless::Function` and others. See other types here : https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html

**Comment by dannysteenman** [comment]
Feel free to create a PR I'd be happy to merge it!

**Comment by felipe1982** [comment]
Sorry mate, I don't know the first thing about writing extensions... 🤷‍♂️

**Comment by PatMyron** [comment]
related: https://github.com/aws/serverless-application-model/issues/1133

**Comment by dannysteenman** [comment]
> related: [aws/serverless-application-model#1133](https://github.com/aws/serverless-application-model/issues/1133)

@PatMyron thank you for highlighting this! @felipe1982 as soon as there is an spec file available (like @PatMyron pointed out) I could automatically fetch the data and parse it into a snippet like the [cfn resource spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html)

**Comment by garretwilson** [comment]
In addition, even editing a SAM template with this extension incorrectly underlings `!Sub` values. It may be lack of supporting the [`AWS::LanguageExtensions` transform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-languageextensions.html). See [Introducing new language extensions in AWS CloudFormation](https://aws.amazon.com/blogs/mt/introducing-new-language-extensions-in-aws-cloudformation/).

In any case I'm going to uninstall this extension, as it doesn't support AWS SAM and makes editing worse than with no extension.

**Comment by dannysteenman** [comment]
I've now added support for all AWS SAM resources and bumped the extension to version 5, make sure to update the plugin in your vscode to enable the AWS SAM resource completion!

Changelog release: https://github.com/dannysteenman/vscode-cloudformation-snippets/blob/main/CHANGELOG.md#510-2024-04-13
