### ISSUE TITLE
Enable snippets only for *.cfn.yaml files

### ISSUE THREAD

**Issue by ojarosch** [dannysteenman/vscode-cloudformation-snippets#9]
I'm often facing the problem, that vs-code thinks i want to write snippet when i usually just editing a non cfn-yaml file.
Is there a possibility to change the valid fileending to `.cfn.yaml`, maybe as a settings option?

**Comment by dannysteenman** [comment]
I understand the issue and it can be quite annoying, however there's nothing I can do about it in vscode. When you create a snippet you can set the scope to trigger the autocomplete and that is determined by the language. I can't filter on filetype unfortunately.. see docs for more information: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-scope
